<?php

declare(strict_types=1);

namespace Nexus\Manufacturing\Contracts;

use Nexus\Manufacturing\ValueObjects\PlannedOrder;

/**
 * Repository for MRP planned orders.
 *
 * Implementations persist and retrieve planned orders generated by MRP.
 */
interface PlannedOrderRepositoryInterface
{
    /**
     * Save a planned order.
     */
    public function save(PlannedOrder $plannedOrder): void;

    /**
     * Save multiple planned orders.
     *
     * @param array<PlannedOrder> $plannedOrders
     */
    public function saveMany(array $plannedOrders): void;

    /**
     * Find planned orders by product.
     *
     * @return array<PlannedOrder>
     */
    public function findByProduct(string $productId): array;

    /**
     * Find planned orders by work center and date range.
     *
     * @return array<PlannedOrder>
     */
    public function findByWorkCenterAndDateRange(
        string $workCenterId,
        \DateTimeImmutable $startDate,
        \DateTimeImmutable $endDate
    ): array;

    /**
     * Find planned orders by date range.
     *
     * @return array<PlannedOrder>
     */
    public function findByDateRange(
        \DateTimeImmutable $startDate,
        \DateTimeImmutable $endDate
    ): array;

    /**
     * Find planned orders by MRP run ID.
     *
     * @return array<PlannedOrder>
     */
    public function findByMrpRun(string $mrpRunId): array;

    /**
     * Delete planned orders by MRP run ID.
     */
    public function deleteByMrpRun(string $mrpRunId): int;

    /**
     * Delete all planned orders for a product.
     */
    public function deleteByProduct(string $productId): int;

    /**
     * Convert planned order to firm work order.
     *
     * @return string The new work order ID
     */
    public function firmToWorkOrder(PlannedOrder $plannedOrder): string;

    /**
     * Firm multiple planned orders to work orders.
     *
     * @param array<PlannedOrder> $plannedOrders
     * @return array<string> The new work order IDs
     */
    public function firmManyToWorkOrders(array $plannedOrders): array;
}
